import os
import json

def find_dbx_path():
    INFO_PATHS = [r"%APPDATA%\Dropbox\info.json", r"%LOCALAPPDATA%\Dropbox\info.json"]
    for path in INFO_PATHS:
        try:
            with open(os.path.expandvars(path), "r") as f:
                data = json.load(f)
                return list(data.values())[0]["path"]
        except:
            pass

class config :
    dropbox_path = find_dbx_path()

    manage_card_info_col_map = {
        'frmhs_no': 'farm_serial_no',
        'brd_stle_1': 'windowless_breeding_yn',
        'brd_stle_2': 'withwindows_breeding_yn',
        'brd_stle_3': 'greenhouse_breeding_yn',
        'past_occrrnc_at': 'past_occurrence_yn',
        'crwd_hsmp_at': 'crowded_complex_yn',
        'intrcp_dsnfc_fclty_01_at': 'fence_installation_yn',
        'intrcp_dsnfc_fclty_02_at': 'entrance_human_disinfection_yn',
        'intrcp_dsnfc_fclty_03_at': 'entrance_car_disinfection_yn',
        'intrcp_dsnfc_fclty_04_at': 'compost_blocking_facility_yn',
        'intrcp_dsnfc_fclty_05_at': 'pig_house_vent_screen_yn',
        'intrcp_dsnfc_fclty_06_at': 'ante_room_yn',
        'intrcp_dsnfc_fclty_07_at': 'pigpen_dedicated_boots_yn',
        'intrcp_dsnfc_fclty_08_at': 'pigpen_sanitation_facility_yn',
        'intrcp_dsnfc_fclty_09_at': 'pigpen_gap_blocking_net_yn',
        'flfl_01_at': 'pigpen_water_puddle_removal_yn',
        'flfl_02_at': 'lime_application_around_farm_yn',
        'flfl_03_at': 'forbid_straw_and_crop_entry_from_wild_pig_area_yn',
        'flfl_04_at': 'forbid_hunting_and_access_yn',
        'flfl_05_at': 'maintain_cleanliness_and_disinfection_around_manure_feed_bin_yn',
        'flfl_07_at': 'periodic_cleaning_and_disinfection_inside_pigpen_yn',
        'flfl_09_at': 'handwashing_before_entering_pigpen_yn',
        'flfl_10_at': 'change_boots_before_entering_pigpen_yn',
        'enfsn_co': 'employee_count',
        'frgnr_enfsn_co': 'foreigner_employee_count'
    }

    manange_card_info_col = ["windowless_breeding_yn",
                             "withwindows_breeding_yn",
                             "greenhouse_breeding_yn",
                             "past_occurrence_yn",
                             "crowded_complex_yn",
                             "fence_installation_yn",
                             "entrance_human_disinfection_yn",
                             "entrance_car_disinfection_yn",
                             "compost_blocking_facility_yn",
                             "pig_house_vent_screen_yn",
                             "ante_room_yn",
                             "pigpen_dedicated_boots_yn",
                             "pigpen_sanitation_facility_yn",
                             "pigpen_gap_blocking_net_yn",
                             "pigpen_water_puddle_removal_yn",
                             "lime_application_around_farm_yn",
                             "forbid_straw_and_crop_entry_from_wild_pig_area_yn",
                             "forbid_hunting_and_access_yn",
                             "maintain_cleanliness_and_disinfection_around_manure_feed_bin_yn",
                             "periodic_cleaning_and_disinfection_inside_pigpen_yn",
                             "handwashing_before_entering_pigpen_yn",
                             "change_boots_before_entering_pigpen_yn"
                             ]

    column_translation = {
        'present_breeding_livestock_count': '현재사육두수',
        'present_mother_pig_breeding_livestock_count': '모돈사육두수',
        'present_porker_breeding_livestock_count': '비육돈사육두수',
        'average_breeding_livestock_count': '평균사육두수',
        'average_mother_pig_breeding_livestock_count': '모돈 평균사육두수',
        'average_porker_breeding_livestock_count': '비육돈 평균사육두수',

        'breeding_pig_breeding_yn' : '종돈 사육여부',
        'captive_wildboar_breeding_yn' : '멧돼지 사육여부',
        'black_pig_breeding_yn' : '흑돼지 사육여부',
        'common_pig_breeding_yn' : '일반 사육여부',
        'mother_pig_breeding_yn': '모돈 사육여부',
        'porker_breeding_yn': '비육돈 사육여부',

        'infection_farm_top_near_distance': '최근접 1개월 내 농장 발생까지 거리',
        'specimen_picking_top_near_distance_6month': '최근접 6개월 내 야생 발생까지 거리',
        'specimen_picking_top_near_distance_1year': '최근접 1년 내 야생 발생까지 거리',

        'radius_1km_pig_farm_count': '1km 내 양돈 농장 수',
        'radius_3km_pig_farm_count': '3km 내 양돈 농장 수',
        'radius_6km_pig_farm_count': '6km 내 양돈 농장 수',
        'radius_9km_pig_farm_count': '9km 내 양돈 농장 수',
        'radius_12km_pig_farm_count': '12km 내 양돈 농장 수',
        'radius_1km_whole_farm_count': '1km 내 농장 수',
        'radius_3km_whole_farm_count': '3km 내 농장 수',
        'radius_6km_whole_farm_count': '6km 내 농장 수',
        'radius_9km_whole_farm_count': '9km 내 농장 수',
        'radius_12km_whole_farm_count': '12km 내 농장 수',

        'livestock_transport_car_visit_count': '21일 내 가축운반 차량 방문 수',
        'rawmilk_transport_car_visit_count': '21일 내 원유운반 차량 방문 수',
        'animal_medicine_transport_car_visit_count': '21일 내 동물(의)약품운반 차량 방문 수',
        'feed_transport_car_visit_count': '21일 내 사료운반 차량 방문 수',
        'livestock_excreta_transport_car_visit_count': '21일 내 가축분뇨운반 차량 방문 수',
        'beddingstraw_transport_car_visit_count': '21일 내 왕겨.쌀겨.톱밥.깔짚운반 차량 방문 수',
        'compost_transport_car_visit_count': '21일 내 퇴비운반 차량 방문 수',
        'animal_medical_car_visit_count': '21일 내 진료.예방접종 차량 방문 수',
        'artificial_insemination_car_visit_count': '21일 내 인공수정 차량 방문 수',
        'consulting_car_visit_count': '21일 내 컨설팅 차량 방문 수',
        'specimen_picking_diseasecontrol_car_visit_count': '21일 내 시료채취,방역 차량 방문 수',
        'machine_repair_car_visit_count': '21일 내 기계수리 차량 방문 수',
        'egg_transport_car_visit_count': '21일 내 알운반 차량 방문 수',
        'roughage_transport_car_visit_count': '21일 내 조사료운반 차량 방문 수',
        'eggtray_transport_car_visit_count': '21일 내 난좌운반 차량 방문 수',
        'byproducts_transport_car_visit_count': '21일 내 가금부산물운반 차량 방문 수',
        'poultry_shipment_manpower_transport_car_visit_count': '21일 내 가금 출하 상하차 인력운송 차량 방문 수',
        'livestock_breeding_facilities_management_car_visit_count': '21일 내 가축사육시설운영관리 차량 방문 수',
        'livestock_carcass_transport_car_visit_count': '21일 내 가축사체운반 차량 방문 수',

        'infection_livestock_transport_car_visit_count': '발생농장-21일 내 가축운반 차량 방문 수',
        'infection_rawmilk_transport_car_visit_count': '발생농장-21일 내 원유운반 차량 방문 수',
        'infection_animal_medicine_transport_car_visit_count': '발생농장-21일 내 동물(의)약품운반 차량 방문 수',
        'infection_feed_transport_car_visit_count': '발생농장-21일 내 사료운반 차량 방문 수',
        'infection_livestock_excreta_transport_car_visit_count': '발생농장-21일 내 가축분뇨운반 차량 방문 수',
        'infection_beddingstraw_transport_car_visit_count': '발생농장-21일 내 왕겨.쌀겨.톱밥.깔짚운반 차량 방문 수',
        'infection_compost_transport_car_visit_count': '발생농장-21일 내 퇴비운반 차량 방문 수',
        'infection_animal_medical_car_visit_count': '발생농장-21일 내 진료.예방접종 차량 방문 수',
        'infection_artificial_insemination_car_visit_count': '발생농장-21일 내 인공수정 차량 방문 수',
        'infection_consulting_car_visit_count': '발생농장-21일 내 컨설팅 차량 방문 수',
        'infection_specimen_picking_diseasecontrol_car_visit_count': '발생농장-21일 내 시료채취,방역 차량 방문 수',
        'infection_machine_repair_car_visit_count': '발생농장-21일 내 기계수리 차량 방문 수',
        'infection_egg_transport_car_visit_count': '발생농장-21일 내 알운반 차량 방문 수',
        'infection_roughage_transport_car_visit_count': '발생농장-21일 내 조사료운반 차량 방문 수',
        'infection_eggtray_transport_car_visit_count': '발생농장-21일 내 난좌운반 차량 방문 수',
        'infection_byproducts_transport_car_visit_count': '발생농장-21일 내 가금부산물운반 차량 방문 수',
        'infection_poultry_shipment_manpower_transport_car_visit_count': '발생농장-21일 내 가금 출하 상하차 인력운송 차량 방문 수',
        'infection_breeding_facilities_management_car_visit_count': '발생농장-21일 내 가축사육시설운영관리 차량 방문 수',
        'infection_livestock_carcass_transport_car_visit_count': '발생농장-21일 내 가축사체운반 차량 방문 수',
        'infection_whole_car_visit_count' : '발생농장-21일 이내 모든 차량 방문 수',

        'radius_1km_wildboar_count': '1km 내 멧돼지 수',
        'radius_3km_wildboar_count': '3km 내 멧돼지 수',
        'radius_6km_wildboar_count': '6km 내 멧돼지 수',
        'radius_9km_wildboar_count': '9km 내 멧돼지 수',
        'radius_12km_wildboar_count': '12km 내 멧돼지 수',

        '농지지역_밭_1000': '1km 내 농지 지역 비율',
        '농지지역_밭_3000': '3km 내 농지 지역 비율',
        '농지지역_밭_6000': '6km 내 농지 지역 비율',
        '농지지역_밭_9000': '9km 내 농지 지역 비율',
        '농지지역_밭_12000': '12km 내 농지 지역 비율',
        '시가화지역_1000': '1km 내 시가화 지역 비율',
        '시가화지역_3000': '3km 내 시가화 지역 비율',
        '시가화지역_6000': '6km 내 시가화 지역 비율',
        '시가화지역_9000': '9km 내 시가화 지역 비율',
        '시가화지역_12000': '12km 내 시가화 지역 비율',
        '산림지역_고도_1000': '1km 내 산림 지역 비율',
        '산림지역_고도_3000': '3km 내 산림 지역 비율',
        '산림지역_고도_6000': '6km 내 산림 지역 비율',
        '산림지역_고도_9000': '9km 내 산림 지역 비율',
        '산림지역_고도_12000': '12km 내 산림 지역 비율',
        '산림지역_660_1000': '1km 내 산림(660) 지역 비율',
        '산림지역_660_3000': '3km 내 산림(660)  지역 비율',
        '산림지역_660_6000': '6km 내 산림(660)  지역 비율',
        '산림지역_660_9000': '9km 내 산림(660)  지역 비율',
        '산림지역_660_12000': '12km 내 산림(660)  지역 비율',
        '산림지역_10000_1000': '1km 내 산림(10000) 지역 비율',
        '산림지역_10000_3000': '3km 내 산림(10000) 지역 비율',
        '산림지역_10000_6000': '6km 내 산림(10000) 지역 비율',
        '산림지역_10000_9000': '9km 내 산림(10000) 지역 비율',
        '산림지역_10000_12000': '12km 내 산림(10000) 지역 비율',
        '산림지역_2분위수_1000': '1km 내 산림(2분위수) 지역 비율',
        '산림지역_2분위수_3000': '3km 내 산림(2분위수)  지역 비율',
        '산림지역_2분위수_6000': '6km 내 산림(2분위수)  지역 비율',
        '산림지역_2분위수_9000': '9km 내 산림(2분위수)  지역 비율',
        '산림지역_2분위수_12000': '12km 내 산림(2분위수)  지역 비율',
        '산림지역_3분위수_1000': '1km 내 산림(3분위수) 지역 비율',
        '산림지역_3분위수_3000': '3km 내 산림(3분위수) 지역 비율',
        '산림지역_3분위수_6000': '6km 내 산림(3분위수) 지역 비율',
        '산림지역_3분위수_9000': '9km 내 산림(3분위수) 지역 비율',
        '산림지역_3분위수_12000': '12km 내 산림(3분위수) 지역 비율',
        '산림지역_660_고도_1000': '1km 내 산림(660,고도) 지역 비율',
        '산림지역_660_고도_3000': '3km 내 산림(660,고도)  지역 비율',
        '산림지역_660_고도_6000': '6km 내 산림(660,고도)  지역 비율',
        '산림지역_660_고도_9000': '9km 내 산림(660,고도)  지역 비율',
        '산림지역_660_고도_12000': '12km 내 산림(660,고도)  지역 비율',
        '산림지역_10000_고도_1000': '1km 내 산림(10000,고도) 지역 비율',
        '산림지역_10000_고도_3000': '3km 내 산림(10000,고도) 지역 비율',
        '산림지역_10000_고도_6000': '6km 내 산림(10000,고도) 지역 비율',
        '산림지역_10000_고도_9000': '9km 내 산림(10000,고도) 지역 비율',
        '산림지역_10000_고도_12000': '12km 내 산림(10000,고도) 지역 비율',
        '산림지역_2분위수_고도_1000': '1km 내 산림(2분위수,고도) 지역 비율',
        '산림지역_2분위수_고도_3000': '3km 내 산림(2분위수,고도)  지역 비율',
        '산림지역_2분위수_고도_6000': '6km 내 산림(2분위수,고도)  지역 비율',
        '산림지역_2분위수_고도_9000': '9km 내 산림(2분위수,고도)  지역 비율',
        '산림지역_2분위수_고도_12000': '12km 내 산림(2분위수,고도)  지역 비율',
        '산림지역_3분위수_고도_1000': '1km 내 산림(3분위수,고도) 지역 비율',
        '산림지역_3분위수_고도_3000': '3km 내 산림(3분위수,고도) 지역 비율',
        '산림지역_3분위수_고도_6000': '6km 내 산림(3분위수,고도) 지역 비율',
        '산림지역_3분위수_고도_9000': '9km 내 산림(3분위수,고도) 지역 비율',
        '산림지역_3분위수_고도_12000': '12km 내 산림(3분위수,고도) 지역 비율',

        '서식지_1000': '1km 내 서식지 비율',
        '서식지_3000': '3km 내 서식지 비율',
        '서식지_6000': '6km 내 서식지 비율',
        '서식지_9000': '9km 내 서식지 비율',
        '서식지_12000': '12km 내 서식지 비율',

        'nearest_habitat_dist' : '최근접 서식지 거리',

        'elevation_nearest': '고도',
        'elevation_median_500m': '500m 내 고도 중위값',
        'elevation_median_1km': '1km 내 고도 중위값',

        'habitat_possibility_nearest': '서식지 가능성도',
        'habitat_possibility_median_500m': '500m 내 서식지 가능성도 중위값',
        'habitat_possibility_median_1km': '1km 내 서식지 가능성도 중위값',

         'radius_1km_infection_farm_1month_count' : '1km 내 최근 1개월 간 농장발생 개수',
         'radius_3km_infection_farm_1month_count' : '3km 내 최근 1개월 간 농장발생 개수',
         'radius_6km_infection_farm_1month_count' : '6km 내 최근 1개월 간 농장발생 개수',
         'radius_9km_infection_farm_1month_count' : '9km 내 최근 1개월 간 농장발생 개수',
         'radius_12km_infection_farm_1month_count'  : '12km 내 최근 1개월 간 농장발생 개수',
         'radius_1km_specimen_picking_6month_count' : '1km 내 최근 6개월 간 야생발생 개수',
         'radius_3km_specimen_picking_6month_count' : '3km 내 최근 6개월 간 야생발생 개수',
         'radius_6km_specimen_picking_6month_count' : '6km 내 최근 6개월 간 야생발생 개수',
         'radius_9km_specimen_picking_6month_count' : '9km 내 최근 6개월 간 야생발생 개수',
         'radius_12km_specimen_picking_6month_count'  :'12km 내 최근 6개월 간 야생발생 개수',
         'radius_1km_specimen_picking_1year_count' : '1km 내 최근 1년 간 야생발생 개수',
         'radius_3km_specimen_picking_1year_count' : '3km 내 최근 1년 간 야생발생 개수',
         'radius_6km_specimen_picking_1year_count' : '6km 내 최근 1년 간 야생발생 개수',
         'radius_9km_specimen_picking_1year_count' : '9km 내 최근 1년 간 야생발생 개수',
         'radius_12km_specimen_picking_1year_count' :'12km 내 최근 1년 간 야생발생 개수',

        'radius_12km_farmland_area_rate' : '12km 이내 농지 비율',
        'radius_1km_urban_area_rate' : '1km 이내 시가화 비율',
        'radius_1km_forest_area_rate': '1km 이내 산림 비율',
        'radius_9km_wildboar_habitat_area_rate': '9km 이내 서식지 비율',
        'radius_12km_cum_rainfall_1month': '1달 내 12km 이내 누적 강수량',

        'radius_500m_elevation_median' : '500m 이내 고도 중위값',
        'radius_500m_habiatat_possibility_median' : '500m 이내 서식지가능성도 중위값',
        'top_near_wildboar_habitat_distance' : '최근접 서식지와의 거리'
    }

    full_dataset_column_translation = {
        '농지지역_밭_12000' : 'radius_12km_farmland_area_rate',
        '시가화지역_1000' : 'radius_1km_urban_area_rate',
        'elevation_median_500m' : 'radius_500m_elevation_median',
        'habitat_possibility_median_500m' : 'radius_500m_habiatat_possibility_median',
        'nearest_habitat_dist' : 'top_near_wildboar_habitat_distance',
        '산림지역_10000_고도_1000' : 'radius_1km_forest_area_rate',
        '서식지_9000' : 'radius_9km_wildboar_habitat_area_rate'
    }

    training_set_col = [
                'standard_date',
                'farm_serial_no',
                'farm_coordinate',
                'farm_longitude',
                'farm_latitude',
                'radius_12km_farmland_area_rate',
                'radius_1km_urban_area_rate',
                'radius_1km_forest_area_rate',
                'radius_9km_wildboar_habitat_area_rate',
                'top_near_wildboar_habitat_distance',
                'radius_500m_elevation_median',
                'radius_500m_habiatat_possibility_median',
                'radius_12km_cum_rainfall_1month',
                'infection_farm_top_near_distance',
                'radius_6km_infection_farm_1month_count',
                'specimen_picking_top_near_distance_6month',
                'radius_6km_specimen_picking_6month_count',
                'radius_12km_whole_farm_count',
                'radius_12km_pig_farm_count',
                'present_breeding_livestock_count',
                'present_mother_pig_breeding_livestock_count',
                'present_porker_breeding_livestock_count',
                'average_breeding_livestock_count',
                'average_mother_pig_breeding_livestock_count',
                'average_porker_breeding_livestock_count',
                'breeding_pig_breeding_yn',
                'captive_wildboar_breeding_yn',
                'black_pig_breeding_yn',
                'common_pig_breeding_yn',
                'mother_pig_breeding_yn',
                'porker_breeding_yn',
                'windowless_breeding_yn',
                'withwindows_breeding_yn',
                'greenhouse_breeding_yn',
                'past_occurrence_yn',
                'crowded_complex_yn',
                'fence_installation_yn',
                'entrance_human_disinfection_yn',
                'entrance_car_disinfection_yn',
                'compost_blocking_facility_yn',
                'pig_house_vent_screen_yn',
                'ante_room_yn',
                'pigpen_dedicated_boots_yn',
                'pigpen_sanitation_facility_yn',
                'pigpen_gap_blocking_net_yn',
                'pigpen_water_puddle_removal_yn',
                'lime_application_around_farm_yn',
                'forbid_straw_and_crop_entry_from_wild_pig_area_yn',
                'forbid_hunting_and_access_yn',
                'maintain_cleanliness_and_disinfection_around_manure_feed_bin_yn',
                'periodic_cleaning_and_disinfection_inside_pigpen_yn',
                'handwashing_before_entering_pigpen_yn',
                'change_boots_before_entering_pigpen_yn',
                'livestock_transport_car_visit_count',
                'animal_medicine_transport_car_visit_count',
                'feed_transport_car_visit_count',
                'livestock_excreta_transport_car_visit_count',
                'beddingstraw_transport_car_visit_count',
                'compost_transport_car_visit_count',
                'animal_medical_car_visit_count',
                'artificial_insemination_car_visit_count',
                'consulting_car_visit_count',
                'roughage_transport_car_visit_count',
                'livestock_breeding_facilities_management_car_visit_count',
                'livestock_carcass_transport_car_visit_count',
                'infection_livestock_transport_car_visit_count',
                'infection_animal_medicine_transport_car_visit_count',
                'infection_feed_transport_car_visit_count',
                'infection_livestock_excreta_transport_car_visit_count',
                'infection_beddingstraw_transport_car_visit_count',
                'infection_compost_transport_car_visit_count',
                'infection_animal_medical_car_visit_count',
                'infection_artificial_insemination_car_visit_count',
                'infection_consulting_car_visit_count',
                'infection_roughage_transport_car_visit_count',
                'infection_breeding_facilities_management_car_visit_count',
                'infection_livestock_carcass_transport_car_visit_count',
                'infection_whole_car_visit_count',
                'asf_occurrence_yn'
                ]